name: Power Platform Export and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      # ✅ Étape pour s'assurer que NuGet est accessible dans le PATH
      - name: 🧰 Add NuGet to PATH (self-hosted fix)
        run: |
          Write-Host "Adding nuget.exe to PATH..."
          $nugetPath = "C:\Windows\System32"
          $env:PATH = "$nugetPath;$env:PATH"
          Write-Host "NuGet version check:"
          nuget help
        shell: pwsh

      # ⚙️ Installation automatique des Power Platform Tools
      - name: ⚙️ Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      # ✅ Forcer le chemin du PAC CLI local (celui installé via dotnet)
      - name: 🔧 Force PAC path for self-hosted runner
        run: |
          Write-Host "Setting PAC_PATH to .dotnet global tools path..."
          echo "PAC_PATH=$env:USERPROFILE\.dotnet\tools\pac.exe" >> $env:GITHUB_ENV
        shell: pwsh

      # Vérifier que pac.exe est bien trouvé
      - name: 🔍 Verify PAC installation
        run: |
          Write-Host "PAC path: $env:PAC_PATH"
          & $env:PAC_PATH help
        shell: pwsh

      # 📦 Exporter la solution
      - name: 📦 Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}
          solution-name: 'aSolution'
          solution-output-file: 'aSolution.zip'
          working-directory: 'out'
        env:
          POWERPLATFORMTOOLS_PACINSTALLED: true
          POWERPLATFORMTOOLS_PACPATH: ${{ env.PAC_PATH }}

      # 📂 Décompresser la solution
      - name: 📂 Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/aSolution.zip'
          solution-folder: 'out/solutions/solution-one'
          solution-type: 'Unmanaged'
          overwrite-files: true
        env:
          POWERPLATFORMTOOLS_PACPATH: ${{ env.PAC_PATH }}

      # 🚀 Publier la solution
      - name: 🚀 Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}
        env:
          POWERPLATFORMTOOLS_PACPATH: ${{ env.PAC_PATH }}

      # 🧾 Commit des changements éventuels
      - name: 🧾 Commit solution changes
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/solution-one'
          solution-target-folder: 'src/solutions/solution1'
          token: ${{ secrets.GIT_TOKEN }}
