name: Power Platform Export and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      # --- Copie du PAC CLI dans le workspace ---
      - name: ⚙️ Préparer Power Platform CLI pour le runner
        run: |
          $source = "C:\Users\yannm\.dotnet\tools"
          $destination = "$env:GITHUB_WORKSPACE\pac"
          if (-Not (Test-Path $destination)) {
            New-Item -ItemType Directory -Path $destination | Out-Null
          }
          Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force
          Write-Host "✅ pac.exe copié dans le workspace: $destination"
          Get-ChildItem -Path $destination
        shell: pwsh

      # --- Vérification de l'exécutable PAC ---
      - name: 🔍 Vérifier l’exécutable PAC
        run: |
          $pacPath = "$env:GITHUB_WORKSPACE\pac\pac.exe"
          if (-Not (Test-Path $pacPath)) {
            Write-Error "❌ pac.exe introuvable dans $pacPath"
            exit 1
          }
          Write-Host "✅ PAC CLI détecté à $pacPath"
          & $pacPath help | Out-Null
        shell: pwsh

      # --- Export de la solution ---
      - name: 📦 Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}
          solution-name: 'aSolution'
          solution-output-file: 'aSolution.zip'
          working-directory: 'out'
          managed: false
          run-asynchronously: false
        env:
          POWERPLATFORMTOOLS_PACINSTALLED: true
          POWERPLATFORMTOOLS_PACPATH: ${{ github.workspace }}\pac\pac.exe

      # --- Décompression ---
      - name: 📂 Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/aSolution.zip'
          solution-folder: 'out/solutions/solution-one'
          solution-type: 'Unmanaged'
          overwrite-files: true
        env:
          POWERPLATFORMTOOLS_PACPATH: ${{ github.workspace }}\pac\pac.exe

      # --- Publication ---
      - name: 🚀 Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}
        env:
          POWERPLATFORMTOOLS_PACPATH: ${{ github.workspace }}\pac\pac.exe

      # --- Commit final ---
      - name: 🧾 Commit solution changes
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/solution-one'
          solution-target-folder: 'src/solutions/solution1'
          token: ${{ secrets.GIT_TOKEN }}
