name: Power Platform Demo Actions

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Afficher un message de test
      - name: Hello from Yann's Runner 👋
        run: echo "✅ Workflow démarré sur le runner local de Yann !"

      # Étape 3 : Installation du Power Platform CLI depuis NuGet
      - name: Install Power Platform CLI
        shell: powershell
        run: |
          Write-Host "Installing Power Platform CLI..."
          $cliPath = "$env:USERPROFILE\.nuget\packages\microsoft.powerapps.cli\1.50.1\tools\pac.exe"

          if (-Not (Test-Path $cliPath)) {
            Write-Host "Downloading and installing Power Platform CLI via winget..."
            winget install --id Microsoft.PowerAppsCLI -e --source msstore --accept-package-agreements --accept-source-agreements
          } else {
            Write-Host "Power Platform CLI already installed at $cliPath"
          }

          # Vérifie que pac est accessible
          if (Test-Path $cliPath) {
            Write-Host "✅ PAC found at: $cliPath"
            & $cliPath help
            echo "PAC_PATH=$cliPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } else {
            Write-Error "❌ PAC not found after installation."
            exit 1
          }

      # Étape 4 : Authentification à Power Platform
      - name: Authenticate to Power Platform
        shell: powershell
        run: |
          Write-Host "🔐 Authenticating..."
          & $env:PAC_PATH auth clear
          & $env:PAC_PATH auth create --url https://org643d7b2c.crm12.dynamics.com --username "nicoise.nkounkou@edu.igensia.com" --password $env:PASSWORD
          & $env:PAC_PATH auth list
        env:
          PASSWORD: ${{ secrets.PASSWORD }}

      # Étape 5 : Exporter la solution
      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}
          solution-name: 'aSolution'
          solution-output-file: 'aSolution.zip'
          working-directory: 'out'

      # Étape 6 : Décompacter la solution
      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/aSolution.zip'
          solution-folder: 'out/solutions/solution-one'
          solution-type: 'Unmanaged'
          overwrite-files: true

      # Étape 7 : Publier la solution
      - name: Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}

      # Étape 8 : Préparer les changements pour le commit
      - name: Prepare solution changes for check-in into source control
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/solution-one'
          solution-target-folder: 'src/solutions/solution1'
          token: ${{ secrets.GIT_TOKEN }}
