name: Power Platform CI/CD (Local Runner)

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      # 🧱 Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # ⚙️ Étape 2 : Vérifier et trouver le CLI Power Platform
      - name: Locate Power Platform CLI
        shell: pwsh
        run: |
          Write-Host "🔍 Searching for pac.exe..."
          $pacPath = "$env:LOCALAPPDATA\Microsoft\PowerAppsCLI\pac.cmd"
          if (-Not (Test-Path $pacPath)) {
            Write-Host "⚠️ PAC not found. Installing Power Platform CLI..."
            winget install --id Microsoft.PowerAppsCLI -e --accept-package-agreements --accept-source-agreements
          } else {
            Write-Host "✅ PAC found at: $pacPath"
          }
          echo "PAC_PATH=$pacPath" | Out-File -FilePath $env:GITHUB_ENV -Append

      # 🔐 Étape 3 : Authentification (profil local requis)
      - name: Authenticate to Power Platform
        shell: pwsh
        run: |
          Write-Host "🔐 Authenticating with existing PAC profile..."
          & $env:PAC_PATH auth list
        continue-on-error: true

      # 📦 Étape 4 : Export de la solution
      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}
          solution-name: 'aSolution'
          solution-output-file: 'aSolution.zip'
          working-directory: 'out'

      # 🧩 Étape 5 : Décompactage de la solution
      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/aSolution.zip'
          solution-folder: 'out/solutions/solution-one'
          solution-type: 'Unmanaged'
          allowWrite: true
          clobber: true

      # 🚀 Étape 6 : Publication de la solution
      - name: Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}

      # 🪄 Étape 7 : Commit Git si des modifications existent
      - name: Commit solution changes
        shell: pwsh
        run: |
          if (Test-Path "out/solutions/solution-one") {
            Write-Host "💾 Preparing commit..."
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add out/solutions/solution-one
            git diff --cached --quiet || git commit -m "Update solution-one via CI"
            git push origin master
          } else {
            Write-Host "✅ Rien à committer (aucun changement détecté)."
          }
