name: Power Platform Demo Actions

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Confirm PowerShell 7
        run: pwsh -v

      - name: Locate Power Platform CLI
        id: find_pac
        shell: pwsh
        run: |
          $pacPath = "$env:USERPROFILE\.nuget\packages\microsoft.powerapps.cli\1.50.1\tools\pac.exe"
          if (-Not (Test-Path $pacPath)) {
            Write-Error "❌ pac.exe introuvable à $pacPath"
            exit 1
          }
          Write-Host "✅ pac.exe trouvé à $pacPath"
          echo "PAC_PATH=$pacPath" >> $env:GITHUB_ENV

      - name: Set environment variable for Power Platform Tools
        run: echo "POWERPLATFORMTOOLS_PACPATH=$env:PAC_PATH" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Install Power Platform Actions
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        env:
          POWERPLATFORMTOOLS_PACPATH: ${{ env.PAC_PATH }}
          POWERPLATFORMTOOLS_PACINSTALLED: true
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}
          solution-name: 'aSolution'
          solution-output-file: 'aSolution.zip'
          working-directory: 'out'

      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/aSolution.zip'
          solution-folder: 'out/solutions/solution-one'
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        env:
          POWERPLATFORMTOOLS_PACPATH: ${{ env.PAC_PATH }}
          POWERPLATFORMTOOLS_PACINSTALLED: true
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}

      - name: Prepare solution changes for check-in into source control
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/solution-one'
          solution-target-folder: 'src/solutions/solution1'
          token: ${{ secrets.GIT_TOKEN }}
