name: Power Platform Export and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: 🔧 Force PAC path for self-hosted runner
        run: |
          Write-Host "Setting PAC_PATH to local pac.exe..."
          echo "PAC_PATH=C:\Users\yannm\AppData\Local\Microsoft\PowerAppsCLI\tools\pac.exe" >> $env:GITHUB_ENV
        shell: pwsh

      - name: 🔍 Verify PAC installation
        run: |
          Write-Host "PAC path: $env:PAC_PATH"
          & $env:PAC_PATH --version
        shell: pwsh

      - name: 📦 Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}
          solution-name: 'aSolution'
          solution-output-file: 'aSolution.zip'
          working-directory: 'out'
        env:
          POWERPLATFORMTOOLS_PACINSTALLED: true
          POWERPLATFORMTOOLS_PACPATH: C:\Users\yannm\AppData\Local\Microsoft\PowerAppsCLI\tools\pac.exe

      - name: 📂 Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/aSolution.zip'
          solution-folder: 'out/solutions/solution-one'
          solution-type: 'Unmanaged'
          overwrite-files: true
        env:
          POWERPLATFORMTOOLS_PACPATH: C:\Users\yannm\AppData\Local\Microsoft\PowerAppsCLI\tools\pac.exe

      - name: 🚀 Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}
        env:
          POWERPLATFORMTOOLS_PACPATH: C:\Users\yannm\AppData\Local\Microsoft\PowerAppsCLI\tools\pac.exe

      - name: 🧾 Commit solution changes
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/solution-one'
          solution-target-folder: 'src/solutions/solution1'
          token: ${{ secrets.GIT_TOKEN }}
