name: Power Platform Export and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      # ✅ Vérifie que nuget est disponible
      - name: 🧰 Ensure NuGet is available
        run: |
          $nugetPath = "C:\Windows\System32\nuget.exe"
          if (-Not (Test-Path $nugetPath)) {
            Write-Host "NuGet not found, downloading..."
            Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe" -OutFile $nugetPath
          }
          Write-Host "NuGet is ready at $nugetPath"
          & $nugetPath help
        shell: pwsh

      # ✅ Vérifie et installe Power Platform CLI si manquant
      - name: ⚙️ Ensure Power Platform CLI
        run: |
          $pacPath = "$env:USERPROFILE\.dotnet\tools\pac.exe"
          if (-Not (Test-Path $pacPath)) {
            Write-Host "PAC CLI not found, installing..."
            dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          } else {
            Write-Host "PAC CLI already installed at $pacPath"
          }
          Write-Host "PAC CLI available at: $pacPath"
          & $pacPath help
          echo "PAC_PATH=$pacPath" >> $env:GITHUB_ENV
        shell: pwsh

      # ✅ Installe les outils Power Platform
      - name: 🧱 Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1
        env:
          NUGET_EXE_PATH: C:\Windows\System32\nuget.exe

      # 🔍 Vérifie la version PAC (debug)
      - name: 🔍 Verify PAC CLI
        run: |
          Write-Host "PAC path: $env:PAC_PATH"
          & $env:PAC_PATH help
        shell: pwsh

      # 📦 Exporte la solution
      - name: 📦 Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}
          solution-name: 'aSolution'
          solution-output-file: 'aSolution.zip'
          working-directory: 'out'
        env:
          POWERPLATFORMTOOLS_PACINSTALLED: true
          POWERPLATFORMTOOLS_PACPATH: ${{ env.PAC_PATH }}

      # 📂 Décompresse la solution
      - name: 📂 Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/aSolution.zip'
          solution-folder: 'out/solutions/solution-one'
          solution-type: 'Unmanaged'
          overwrite-files: true
        env:
          POWERPLATFORMTOOLS_PACPATH: ${{ env.PAC_PATH }}

      # 🚀 Publie la solution
      - name: 🚀 Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}
        env:
          POWERPLATFORMTOOLS_PACPATH: ${{ env.PAC_PATH }}

      # 🧾 Commit les changements
      - name: 🧾 Commit solution changes
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/solution-one'
          solution-target-folder: 'src/solutions/solution1'
          token: ${{ secrets.GIT_TOKEN }}
