name: Power Platform Demo Actions

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    # ✅ Microsoft recommande Windows (et ton runner self-hosted est Windows)
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Étape officielle d’installation des Power Platform Tools
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      # ✅ Export de la solution depuis ton environnement Power Platform
      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}
          solution-name: 'aSolution'
          solution-output-file: 'aSolution.zip'
          working-directory: 'out'

      # ✅ Décompactage (Unpack) de la solution pour Git
      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/aSolution.zip'
          solution-folder: 'out/solutions/solution-one'
          solution-type: 'Unmanaged'
          overwrite-files: true

      # ✅ Publication de la solution dans ton environnement
      - name: Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}

      # ✅ Commit automatique des modifications dans ton dépôt GitHub
      - name: Prepare solution changes for check-in into source control
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/solution-one'
          solution-target-folder: 'src/solutions/solution1'
          token: ${{ secrets.GIT_TOKEN }}
