name: Power Platform Export and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      # --- 🧩 Cloner le dépôt ---
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      # --- ⚙️ Préparer Power Platform CLI ---
      - name: ⚙️ Préparer Power Platform CLI pour le runner
        run: |
          $source = "C:\Users\yannm\.dotnet\tools"
          $destination = "C:\Users\yannm\actions-runner\_work\PowerAppsProject\PowerAppsProject\pac"
          
          if (-Not (Test-Path $destination)) {
            New-Item -ItemType Directory -Path $destination | Out-Null
          }

          Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force
          Write-Host "✅ pac.exe copié dans le workspace: $destination"
          Get-ChildItem -Path $destination
        shell: pwsh

      # --- 🔍 Vérification de l'installation PAC ---
      - name: 🔍 Verify PAC installation
        run: |
          $pacPath = "C:\Users\yannm\actions-runner\_work\PowerAppsProject\PowerAppsProject\pac\pac.exe"
          if (-Not (Test-Path $pacPath)) {
            Write-Error "❌ pac.exe introuvable dans $pacPath — vérifie l'installation."
            exit 1
          }
          Write-Host "✅ PAC CLI détecté dans $pacPath"
          & $pacPath help
        shell: pwsh

      # --- 📦 Export de la solution ---
      - name: 📦 Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}
          solution-name: 'aSolution'
          solution-output-file: 'aSolution.zip'
          working-directory: 'out'
          managed: false
          run-asynchronously: false
        env:
          POWERPLATFORMTOOLS_PACINSTALLED: true
          POWERPLATFORMTOOLS_PACPATH: C:\Users\yannm\actions-runner\_work\PowerAppsProject\PowerAppsProject\pac\pac.exe
          PAC_PATH: C:\Users\yannm\actions-runner\_work\PowerAppsProject\PowerAppsProject\pac\pac.exe

      # --- 📂 Décompression de la solution ---
      - name: 📂 Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/aSolution.zip'
          solution-folder: 'out/solutions/solution-one'
          solution-type: 'Unmanaged'
          overwrite-files: true
        env:
          POWERPLATFORMTOOLS_PACPATH: C:\Users\yannm\actions-runner\_work\PowerAppsProject\PowerAppsProject\pac\pac.exe

      # --- 🚀 Publication de la solution ---
      - name: 🚀 Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: 'https://org643d7b2c.crm12.dynamics.com'
          user-name: 'nicoise.nkounkou@edu.igensia.com'
          password-secret: ${{ secrets.PASSWORD }}
        env:
          POWERPLATFORMTOOLS_PACPATH: C:\Users\yannm\actions-runner\_work\PowerAppsProject\PowerAppsProject\pac\pac.exe

      # --- 🧾 Commit des changements ---
      - name: 🧾 Commit solution changes
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/solution-one'
          solution-target-folder: 'src/solutions/solution1'
          token: ${{ secrets.GIT_TOKEN }}
