name: Power Platform Demo Actions

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted  # ✅ ton runner local

    steps:
      # 🧩 Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🧩 Étape 2 : Installer Node.js 18 (pour compatibilité CLI)
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 🧩 Étape 3 : Installer la Power Platform CLI officielle
      - name: Install Microsoft Power Platform CLI
        run: |
          npm install -g @microsoft/powerplatform-cli@latest
          pac --version

      # 🧩 Étape 4 : Authentifier dans Power Platform (vérification)
      - name: Check Power Platform Authentication
        run: |
          pac auth clear
          pac auth create --url https://org643d7b2c.crm12.dynamics.com --username nicoise.nkounkou@edu.igensia.com --password $env:PASSWORD
          pac auth list
        env:
          PASSWORD: ${{ secrets.PASSWORD }}

      # 🧩 Étape 5 : Exporter la solution
      - name: Export Solution
        run: |
          mkdir out
          pac solution export `
            --path out/aSolution.zip `
            --name aSolution `
            --environment https://org643d7b2c.crm12.dynamics.com
        env:
          PASSWORD: ${{ secrets.PASSWORD }}

      # 🧩 Étape 6 : Décompresser la solution
      - name: Unpack Solution
        run: |
          pac solution unpack `
            --zipfile out/aSolution.zip `
            --folder out/solutions/solution-one `
            --allowDelete true `
            --overwrite true

      # 🧩 Étape 7 : Publier la solution
      - name: Publish Solution
        run: |
          pac solution publish `
            --environment https://org643d7b2c.crm12.dynamics.com

      # 🧩 Étape 8 : Préparer les changements pour commit
      - name: Prepare solution changes for check-in into source control
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/solution-one'
          solution-target-folder: 'src/solutions/solution1'
          token: ${{ secrets.GIT_TOKEN }}
